theme: jekyll-theme-minimal
title: Williams Family Church Blog
logo: /assets/img/stain.jpg
description: Thinking out loud. Trying to save a dying church. Christ is LORD.
github:
  is_project_page: false