github:
    is_project_page: false
theme: jekyll-theme-leap-day
title: Williams Family Church Blog
description: Thinking out loud. Trying to save a dying church. Christ is LORD.
github:
  is_project_page: false
